- name: Install Outline VPN and Send API to Telegram
  hosts: all
  gather_facts: false
  become: true

  vars:
    telegram_bot_token: "7863276254:AAESQyj_pHTwoWmMgC9sU0Hlz_rY3FjKZLg"
    telegram_chat_id: "215742545"

  tasks:
    - name: Ensure wget and curl are installed
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - wget
        - curl

    - name: Run Outline install script
      shell: |
        sudo bash -c "$(wget -qO- https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh)"
      register: install_result
      args:
        executable: /bin/bash

    - name: Extract API JSON from output
      set_fact:
        outline_api: "{{ install_result.stdout | regex_search('{.*}', '\\\\{.*\\\\}') }}"

    - name: Print API JSON (optional)
      debug:
        msg: |
          ==== {{ inventory_hostname }} ====
          {{ outline_api }}
      when: outline_api != ""

    - name: Send API JSON to Telegram
      uri:
        url: "https://api.telegram.org/bot{{ telegram_bot_token }}/sendMessage"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          chat_id: "{{ telegram_chat_id }}"
          text: |
            ✅ *Outline VPN Installed*
            *Host:* `{{ inventory_hostname }}`
            *API JSON:*
            ```json
            {{ outline_api }}
            ```
          parse_mode: markdown
      when: outline_api != ""

    - name: Notify if Outline install failed
      uri:
        url: "https://api.telegram.org/bot{{ telegram_bot_token }}/sendMessage"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          chat_id: "{{ telegram_chat_id }}"
          text: "❌ Gagal install Outline VPN di *{{ inventory_hostname }}*."
          parse_mode: markdown
      when: outline_api == ""